using System.Net;
using System.Text;
using GlitchPilot.Core.Models;

namespace GlitchPilot.Core.Rendering;

public static class TriageReportRenderer
{
    public static string RenderQuietNight(string projectSlug, int scannedCount, int hours) => $"""
        <!DOCTYPE html>
        <html><head><meta charset="utf-8"></head>
        <body style="margin:0;padding:0;background:#f0f2f5;font-family:-apple-system,Segoe UI,Roboto,sans-serif;">
        <table width="100%" cellpadding="0" cellspacing="0" style="background:#f0f2f5;padding:24px 0;">
        <tr><td align="center">
        <table width="600" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:12px;overflow:hidden;">
          <tr><td style="background:linear-gradient(135deg,#0f172a,#1e293b);padding:28px 36px;">
            <h1 style="margin:0;color:#f8fafc;font-size:22px;font-weight:600;">GlitchPilot: {Esc(projectSlug)}</h1>
          </td></tr>
          <tr><td style="padding:40px 36px;text-align:center;">
            <div style="font-size:52px;line-height:1;">&#9989;</div>
            <h2 style="color:#16a34a;margin:16px 0 8px;">All clear</h2>
            <p style="color:#64748b;font-size:15px;margin:0;">
              Scanned {scannedCount} {Plural(scannedCount, "error")} from the past {hours}h — nothing needs attention.
            </p>
          </td></tr>
          <tr><td style="padding:0 36px 20px;text-align:center;">
            <p style="color:#94a3b8;font-size:12px;margin:0;">
              Generated by GlitchPilot at {LocalNow()}
            </p>
          </td></tr>
        </table></td></tr></table>
        </body></html>
        """;

    public static string RenderSummary(string projectSlug, List<TriageOutcome> outcomes,
        string environment = "", int minOccurrences = 1, int lookbackHours = 24)
    {
        var actionable = outcomes.Where(o => o.Verdict.RequiresAction).ToList();
        var dismissed = outcomes.Where(o => !o.Verdict.RequiresAction).ToList();

        var html = new StringBuilder();
        html.Append($"""
            <!DOCTYPE html>
            <html><head><meta charset="utf-8"></head>
            <body style="margin:0;padding:0;background:#f0f2f5;font-family:-apple-system,Segoe UI,Roboto,sans-serif;">
            <table width="100%" cellpadding="0" cellspacing="0" style="background:#f0f2f5;padding:24px 0;">
            <tr><td align="center">
            <table width="600" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:12px;overflow:hidden;">
              <tr><td style="background:linear-gradient(135deg,#0f172a,#1e293b);padding:28px 36px;">
                <h1 style="margin:0;color:#f8fafc;font-size:22px;font-weight:600;">GlitchPilot: {Esc(projectSlug)}</h1>
                <p style="color:#94a3b8;font-size:13px;margin:6px 0 0;">
                  {actionable.Count} actionable · {dismissed.Count} dismissed · {outcomes.Count} total
                </p>
              </td></tr>
              <tr><td style="padding:28px 36px;">
            """);

        // Actionable issues
        if (actionable.Count > 0)
        {
            html.Append("<h2 style=\"font-size:16px;color:#0f172a;margin:0 0 16px;\">Requires Attention</h2>");

            foreach (var o in actionable)
            {
                var accent = PriorityColor(o.Verdict.Priority);
                var title = !string.IsNullOrWhiteSpace(o.Verdict.IssueTitle)
                    ? o.Verdict.IssueTitle : o.Candidate.ErrorTitle;
                var summary = !string.IsNullOrWhiteSpace(o.Verdict.EmailSummary)
                    ? o.Verdict.EmailSummary : o.Verdict.Explanation;
                var ghLine = BuildGitHubStatusLine(o);

                html.Append($"""
                    <div style="background:#f8fafc;border-left:4px solid {accent};border-radius:8px;padding:14px 16px;margin-bottom:12px;">
                      <div style="font-size:14px;font-weight:600;color:#0f172a;">
                        <a href="{Esc(o.Candidate.GlitchTipLink)}" style="color:#0f172a;text-decoration:none;">[#{Esc(o.Candidate.ErrorId)}] {Esc(title)}</a>
                      </div>
                      <div style="font-size:12px;color:#94a3b8;margin-top:4px;">
                        <span style="display:inline-block;background:{accent};color:#fff;border-radius:4px;padding:1px 6px;font-size:11px;font-weight:600;">{Esc(o.Verdict.Priority)}</span>
                        {Esc(o.Verdict.ErrorType)} · {o.Candidate.Occurrences}x · {Esc(o.Candidate.SourceLocation ?? "—")}
                      </div>
                      <div style="font-size:13px;color:#475569;margin-top:8px;line-height:1.5;">
                        {Esc(summary)}
                      </div>
                      {ghLine}
                    </div>
                    """);
            }
        }

        // Dismissed issues
        if (dismissed.Count > 0)
        {
            html.Append($"<h2 style=\"font-size:16px;color:#94a3b8;margin:24px 0 12px;\">Dismissed ({dismissed.Count})</h2>");

            foreach (var o in dismissed)
            {
                var title = !string.IsNullOrWhiteSpace(o.Verdict.IssueTitle)
                    ? o.Verdict.IssueTitle : o.Candidate.ErrorTitle;
                var summary = !string.IsNullOrWhiteSpace(o.Verdict.EmailSummary)
                    ? o.Verdict.EmailSummary : o.Verdict.Explanation;

                html.Append($"""
                    <div style="background:#f8fafc;border-left:4px solid #94a3b8;border-radius:8px;padding:14px 16px;margin-bottom:12px;">
                      <div style="font-size:14px;font-weight:600;color:#64748b;">
                        <a href="{Esc(o.Candidate.GlitchTipLink)}" style="color:#64748b;text-decoration:none;">[#{Esc(o.Candidate.ErrorId)}] {Esc(title)}</a>
                      </div>
                      <div style="font-size:12px;color:#94a3b8;margin-top:4px;">
                        {Esc(o.Verdict.ErrorType)} · {o.Candidate.Occurrences}x · {Esc(o.Candidate.SourceLocation ?? "—")}
                      </div>
                      <div style="font-size:13px;color:#94a3b8;margin-top:8px;line-height:1.5;">
                        {Esc(summary)}
                      </div>
                    </div>
                    """);
            }
        }

        html.Append($"""
              </td></tr>
              <tr><td style="padding:16px 36px 20px;text-align:center;border-top:1px solid #e2e8f0;">
                <p style="color:#94a3b8;font-size:12px;margin:0 0 4px;">
                  Filter: ≥{minOccurrences} {(minOccurrences == 1 ? "Event" : "Events")} · Environment: {Esc(environment)} · Last {lookbackHours}h
                </p>
                <p style="color:#94a3b8;font-size:12px;margin:0;">
                  Generated by GlitchPilot at {LocalNow()}
                </p>
              </td></tr>
            </table></td></tr></table>
            </body></html>
            """);

        return html.ToString();
    }

    private static string BuildGitHubStatusLine(TriageOutcome o)
    {
        if (!o.GitHubIssueNumber.HasValue) return "";

        var issueUrl = o.GitHubIssueUrl ?? "";
        return $"""
            <div style="font-size:12px;margin-top:8px;padding-top:8px;border-top:1px solid #e2e8f0;">
              <a href="{Esc(issueUrl)}" style="color:#3b82f6;text-decoration:none;">GitHub issue #{o.GitHubIssueNumber}</a>
            </div>
            """;
    }

    private static string PriorityColor(string priority) => priority switch
    {
        "critical" => "#dc2626",
        "high"     => "#ea580c",
        "medium"   => "#d97706",
        _          => "#94a3b8",
    };

    private static string Esc(string text) => WebUtility.HtmlEncode(text);

    private static string Plural(int count, string word) =>
        count == 1 ? word : word + "s";

    private static string LocalNow() =>
        DateTimeOffset.Now.ToString("yyyy-MM-dd HH:mm");

    private static string Truncate(string text, int max) =>
        text.Length > max ? text[..(max - 3)] + "..." : text;
}
